# Generated by Django 2.2.28 on 2026-02-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20260209_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
